// One-click storefront themes: theme settings + section layout in one tap.
// Applying a template replaces theme settings and the standard sections;
// the seller's own text blocks are preserved and kept after the products.
// Keep in sync with CustomizeClient defaults and lib/sections catalog.

import type { SectionType } from "@/lib/sections";

export type TemplateSettings = Record<string, string | boolean | null>;

export type StoreTemplate = {
  id: string;
  name: string;
  blurb: string;
  swatches: { primary: string; bg: string; text: string };
  settings: TemplateSettings;
  sections: { type: SectionType; visible: boolean }[];
};

export const STORE_TEMPLATES: StoreTemplate[] = [
  {
    id: "essentials",
    name: "Essentials",
    blurb: "Clean, warm and friendly, great for any store.",
    swatches: { primary: "#ed7712", bg: "#faf9f7", text: "#1a1a1a" },
    settings: {
      primary_color: "#ed7712",
      background_color: "#faf9f7",
      text_color: "#1a1a1a",
      accent_color: "#ed7712",
      card_background: "#ffffff",
      font_style: "sans",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "minimal",
      card_border_radius: "md",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "none",
      container_width: "normal",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: false,
      whatsapp_cta: false,
      show_stock_badge: false,
    },
    sections: [
      { type: "announcement", visible: false },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "midnight",
    name: "Midnight Boutique",
    blurb: "Dark, elegant and premium, fashion, beauty, jewelry.",
    swatches: { primary: "#818cf8", bg: "#0f172a", text: "#f1f5f9" },
    settings: {
      primary_color: "#818cf8",
      background_color: "#0f172a",
      text_color: "#f1f5f9",
      accent_color: "#f59e0b",
      card_background: "#1e293b",
      font_style: "elegant",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "shadow",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "centered",
      product_name_size: "large",
      price_style: "large",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Complimentary delivery on orders over ₦50,000",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "forest",
    name: "Forest Fresh",
    blurb: "Calm greens, food, skincare, natural products.",
    swatches: { primary: "#16a34a", bg: "#f0fdf4", text: "#14532d" },
    settings: {
      primary_color: "#16a34a",
      background_color: "#f0fdf4",
      text_color: "#14532d",
      accent_color: "#16a34a",
      card_background: "#ffffff",
      font_style: "friendly",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "bordered",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "relaxed",
      card_border: "light",
      card_shadow: "none",
      container_width: "normal",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: false,
      whatsapp_cta: true,
      show_stock_badge: true,
    },
    sections: [
      { type: "announcement", visible: false },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "sunset",
    name: "Sunset Bold",
    blurb: "Loud and energetic, sneakers, streetwear, thrift.",
    swatches: { primary: "#ea580c", bg: "#fff7ed", text: "#7c2d12" },
    settings: {
      primary_color: "#ea580c",
      background_color: "#fff7ed",
      text_color: "#7c2d12",
      accent_color: "#e11d48",
      card_background: "#ffffff",
      font_style: "bold",
      font_size: "large",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "shadow",
      card_border_radius: "xl",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "left",
      product_name_size: "large",
      price_style: "accent",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "md",
      container_width: "wide",
      product_image_ratio: "landscape",
      show_announcement: true,
      announcement_text: "New drops every Friday, don't sleep on it",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
];
