// One-click storefront themes: theme settings + section layout in one tap.
// Applying a template replaces theme settings and the standard sections;
// the seller's own text blocks are preserved and kept after the products.
// Keep in sync with CustomizeClient defaults and lib/sections catalog.

import type { SectionType } from "@/lib/sections";

export type TemplateSettings = Record<string, string | boolean | null>;

export type StoreTemplate = {
  id: string;
  name: string;
  blurb: string;
  industry: string;
  swatches: { primary: string; bg: string; text: string };
  settings: TemplateSettings;
  sections: { type: SectionType; visible: boolean }[];
};

export const STORE_TEMPLATES: StoreTemplate[] = [
  {
    id: "essentials",
    name: "Essentials",
    blurb: "Clean, warm and friendly, great for any store.",
    industry: "General",
    swatches: { primary: "#ed7712", bg: "#faf9f7", text: "#1a1a1a" },
    settings: {
      primary_color: "#ed7712",
      background_color: "#faf9f7",
      text_color: "#1a1a1a",
      accent_color: "#ed7712",
      card_background: "#ffffff",
      banner_url: null,
      font_style: "sans",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "minimal",
      card_border_radius: "md",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Quality you can trust",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "none",
      container_width: "normal",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: false,
      whatsapp_cta: false,
      show_stock_badge: false,
      footer_text: "Thanks for shopping with us!",
    },
    sections: [
      { type: "announcement", visible: false },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "midnight",
    name: "Midnight Boutique",
    blurb: "Dark, elegant and premium, fashion, beauty, jewelry.",
    industry: "Fashion",
    swatches: { primary: "#818cf8", bg: "#0f172a", text: "#f1f5f9" },
    settings: {
      primary_color: "#818cf8",
      background_color: "#0f172a",
      text_color: "#f1f5f9",
      accent_color: "#f59e0b",
      card_background: "#1e293b",
      banner_url: "/landing/hero-seller.jpg",
      font_style: "elegant",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "shadow",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "centered",
      tagline: "Wear the night",
      show_store_name: true,
      product_name_size: "large",
      price_style: "large",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Complimentary delivery on orders over ₦50,000",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Elegance delivered to your doorstep.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "forest",
    name: "Forest Fresh",
    blurb: "Calm greens, food, skincare, natural products.",
    industry: "Food & Drink",
    swatches: { primary: "#16a34a", bg: "#f0fdf4", text: "#14532d" },
    settings: {
      primary_color: "#16a34a",
      background_color: "#f0fdf4",
      text_color: "#14532d",
      accent_color: "#16a34a",
      card_background: "#ffffff",
      banner_url: "/landing/sell-stall.jpg",
      font_style: "friendly",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "bordered",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Fresh and natural, delivered fast",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "relaxed",
      card_border: "light",
      card_shadow: "none",
      container_width: "normal",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: false,
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "From nature, with care.",
    },
    sections: [
      { type: "announcement", visible: false },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "sunset",
    name: "Sunset Bold",
    blurb: "Loud and energetic, sneakers, streetwear, thrift.",
    industry: "Clothing",
    swatches: { primary: "#ea580c", bg: "#fff7ed", text: "#7c2d12" },
    settings: {
      primary_color: "#ea580c",
      background_color: "#fff7ed",
      text_color: "#7c2d12",
      accent_color: "#e11d48",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-1.jpg",
      font_style: "bold",
      font_size: "large",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "shadow",
      card_border_radius: "xl",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "left",
      tagline: "Cop or cry, no dulling",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "md",
      container_width: "wide",
      product_image_ratio: "landscape",
      show_announcement: true,
      announcement_text: "New drops every Friday, don't sleep on it",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Street-certified. No fakes, no stories.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "opulence",
    name: "Lagos Opulence",
    blurb: "Royal purple and gold, perfumes, jewelry, luxury.",
    industry: "Jewelry",
    swatches: { primary: "#c026d3", bg: "#1a0b2e", text: "#fae8ff" },
    settings: {
      primary_color: "#c026d3",
      background_color: "#1a0b2e",
      text_color: "#fae8ff",
      accent_color: "#fbbf24",
      card_background: "#2b1545",
      banner_url: "/landing/auth-side.jpg",
      font_style: "editorial",
      font_size: "large",
      layout: "masonry",
      image_shape: "rounded",
      spacing: "spacious",
      card_style: "glass",
      card_border_radius: "xl",
      product_name_weight: "bold",
      text_align: "center",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "centered",
      tagline: "Luxury you can own",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "relaxed",
      card_border: "light",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Private shopping on WhatsApp, message us anytime",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Crafted for those who know.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "mono",
    name: "Mono Market",
    blurb: "Stark black and white, thrift, books, minimal goods.",
    industry: "General",
    swatches: { primary: "#171717", bg: "#ffffff", text: "#171717" },
    settings: {
      primary_color: "#171717",
      background_color: "#ffffff",
      text_color: "#171717",
      accent_color: "#171717",
      card_background: "#ffffff",
      banner_url: null,
      font_style: "mono",
      font_size: "small",
      layout: "list",
      image_shape: "square",
      spacing: "compact",
      card_style: "bordered",
      card_border_radius: "none",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "short",
      banner_overlay: false,
      header_style: "minimal",
      tagline: "No frills. Just finds.",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "compact",
      card_border: "medium",
      card_shadow: "none",
      container_width: "narrow",
      product_image_ratio: "square",
      show_announcement: true,
      announcement_text: "New thrift bales every Monday",
      show_socials: false,
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Sold as seen. First pay, first serve.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: false },
      { type: "banner", visible: false },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "ocean",
    name: "Ocean Drift",
    blurb: "Cool blues, swimwear, drinks, fresh everyday goods.",
    industry: "Sports",
    swatches: { primary: "#0ea5e9", bg: "#f0f9ff", text: "#0c4a6e" },
    settings: {
      primary_color: "#0ea5e9",
      background_color: "#f0f9ff",
      text_color: "#0c4a6e",
      accent_color: "#0284c7",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-2.jpg",
      font_style: "clean",
      font_size: "medium",
      layout: "horizontal",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "glass",
      card_border_radius: "xl",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Dive into deals",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "light",
      card_shadow: "sm",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Free delivery in Lagos on orders over ₦30,000",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Ride the wave with us.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "rose",
    name: "Rose Glow",
    blurb: "Soft pinks, beauty, skincare, hair, fragrances.",
    industry: "Beauty",
    swatches: { primary: "#e11d48", bg: "#fff1f2", text: "#4c0519" },
    settings: {
      primary_color: "#e11d48",
      background_color: "#fff1f2",
      text_color: "#4c0519",
      accent_color: "#fb7185",
      card_background: "#ffffff",
      banner_url: "/landing/sell-ig.jpg",
      font_style: "rounded",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "shadow",
      card_border_radius: "xl",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Glow up, every day",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "relaxed",
      card_border: "none",
      card_shadow: "md",
      container_width: "normal",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Buy 2 get 1 free on all glosses this week",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Made for your glow.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "savanna",
    name: "Savanna Gold",
    blurb: "Warm ambers, crafts, accessories, home goods.",
    industry: "Crafts",
    swatches: { primary: "#b45309", bg: "#fffbeb", text: "#451a03" },
    settings: {
      primary_color: "#b45309",
      background_color: "#fffbeb",
      text_color: "#451a03",
      accent_color: "#d97706",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-3.jpg",
      font_style: "geometric",
      font_size: "medium",
      layout: "grid4",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "outlined",
      card_border_radius: "lg",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "short",
      banner_overlay: true,
      header_style: "left",
      tagline: "Handmade with pride",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "accent",
      card_shadow: "none",
      container_width: "wide",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: false,
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Crafted in Nigeria, worn everywhere.",
    },
    sections: [
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "announcement", visible: false },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "emerald-night",
    name: "Emerald Night",
    blurb: "Deep green and gold, premium dark store, watches.",
    industry: "Fashion",
    swatches: { primary: "#10b981", bg: "#052e16", text: "#d1fae5" },
    settings: {
      primary_color: "#10b981",
      background_color: "#052e16",
      text_color: "#d1fae5",
      accent_color: "#fbbf24",
      card_background: "#0a3d24",
      banner_url: null,
      font_style: "modern",
      font_size: "medium",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "filled",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "short",
      banner_overlay: false,
      header_style: "centered",
      tagline: "After dark essentials",
      show_store_name: true,
      product_name_size: "large",
      price_style: "large",
      card_padding: "relaxed",
      card_border: "light",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "square",
      show_announcement: true,
      announcement_text: "Midnight deals, up to 20% off till Sunday",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Quality that outlasts the night.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "banner", visible: false },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "lilac",
    name: "Lilac Dream",
    blurb: "Soft purples, stationery, gifts, baby and kids.",
    industry: "Kids",
    swatches: { primary: "#7c3aed", bg: "#f5f3ff", text: "#2e1065" },
    settings: {
      primary_color: "#7c3aed",
      background_color: "#f5f3ff",
      text_color: "#2e1065",
      accent_color: "#a78bfa",
      card_background: "#ffffff",
      banner_url: null,
      font_style: "thin",
      font_size: "large",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "spacious",
      card_style: "minimal",
      card_border_radius: "pill",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "short",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Little joys, wrapped with love",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "relaxed",
      card_border: "none",
      card_shadow: "sm",
      container_width: "normal",
      product_image_ratio: "square",
      show_announcement: false,
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: false,
      footer_text: "Thoughtful gifts for thoughtful people.",
    },
    sections: [
      { type: "header", visible: true },
      { type: "announcement", visible: false },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "banner", visible: false },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "pepper",
    name: "Pepper Red",
    blurb: "Fiery red, food, spices, party supplies, drinks.",
    industry: "Food & Drink",
    swatches: { primary: "#dc2626", bg: "#fef2f2", text: "#450a0a" },
    settings: {
      primary_color: "#dc2626",
      background_color: "#fef2f2",
      text_color: "#450a0a",
      accent_color: "#f97316",
      card_background: "#ffffff",
      banner_url: "/landing/sell-chat.jpg",
      font_style: "clean",
      font_size: "large",
      layout: "list",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "bordered",
      card_border_radius: "md",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "medium",
      banner_overlay: true,
      header_style: "left",
      tagline: "Hot, fresh, straight to you",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "normal",
      card_border: "accent",
      card_shadow: "sm",
      container_width: "narrow",
      product_image_ratio: "landscape",
      show_announcement: true,
      announcement_text: "Weekend owambe packages now available",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Taste the fire.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: false },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "ankara",
    name: "Ankara & Threads",
    blurb: "Rich indigo prints, native wear, tailors, fabrics.",
    industry: "Clothing",
    swatches: { primary: "#312e81", bg: "#eef2ff", text: "#1e1b4b" },
    settings: {
      primary_color: "#312e81",
      background_color: "#eef2ff",
      text_color: "#1e1b4b",
      accent_color: "#c026d3",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-1.jpg",
      font_style: "bold",
      font_size: "large",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "bordered",
      card_border_radius: "lg",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "left",
      tagline: "Rock your prints with pride",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "accent",
      card_shadow: "sm",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Aso-ebi deals, party season is here",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Sewn with love in Nigeria.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "circuit",
    name: "Circuit Hub",
    blurb: "Gadgets, phones, accessories, electronics plug.",
    industry: "Electronics",
    swatches: { primary: "#06b6d4", bg: "#082f49", text: "#e0f2fe" },
    settings: {
      primary_color: "#06b6d4",
      background_color: "#082f49",
      text_color: "#e0f2fe",
      accent_color: "#22d3ee",
      card_background: "#0c4a6e",
      banner_url: null,
      font_style: "modern",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "filled",
      card_border_radius: "md",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "short",
      banner_overlay: false,
      header_style: "left",
      tagline: "Original gadgets, tested and trusted",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "accent",
      card_padding: "normal",
      card_border: "light",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "square",
      show_announcement: true,
      announcement_text: "Free screen guard on every phone this month",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "No fakes. Warranty on everything.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "banner", visible: false },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "hearth",
    name: "Hearth & Home",
    blurb: "Furniture, decor, kitchenware, home essentials.",
    industry: "Home",
    swatches: { primary: "#78716c", bg: "#faf9f7", text: "#292524" },
    settings: {
      primary_color: "#57534e",
      background_color: "#faf9f7",
      text_color: "#292524",
      accent_color: "#b45309",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-3.jpg",
      font_style: "serif",
      font_size: "large",
      layout: "masonry",
      image_shape: "rounded",
      spacing: "spacious",
      card_style: "minimal",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "tall",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Make your house feel like home",
      show_store_name: true,
      product_name_size: "large",
      price_style: "bold",
      card_padding: "relaxed",
      card_border: "none",
      card_shadow: "sm",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: false,
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: false,
      footer_text: "Beautiful spaces, honest prices.",
    },
    sections: [
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "announcement", visible: false },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "gold-standard",
    name: "Gold Standard",
    blurb: "Jewelry, wristwatches, luxe accessories.",
    industry: "Jewelry",
    swatches: { primary: "#a16207", bg: "#fffdf5", text: "#422006" },
    settings: {
      primary_color: "#a16207",
      background_color: "#fffdf5",
      text_color: "#422006",
      accent_color: "#ca8a04",
      card_background: "#ffffff",
      banner_url: "/landing/auth-side.jpg",
      font_style: "elegant",
      font_size: "large",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "bordered",
      card_border_radius: "xl",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: true,
      header_style: "centered",
      tagline: "Shine every single day",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "relaxed",
      card_border: "accent",
      card_shadow: "sm",
      container_width: "normal",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Free gift box on every order",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Timeless pieces, fair prices.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "banner", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "little-stars",
    name: "Little Stars",
    blurb: "Kids wear, toys, baby essentials, school needs.",
    industry: "Kids",
    swatches: { primary: "#eab308", bg: "#fefce8", text: "#422006" },
    settings: {
      primary_color: "#ca8a04",
      background_color: "#fefce8",
      text_color: "#422006",
      accent_color: "#f97316",
      card_background: "#ffffff",
      banner_url: "/landing/showcase-2.jpg",
      font_style: "rounded",
      font_size: "medium",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "shadow",
      card_border_radius: "xl",
      product_name_weight: "bold",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Everything for your little ones",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "md",
      container_width: "wide",
      product_image_ratio: "square",
      show_announcement: true,
      announcement_text: "Back-to-school sale, up to 25% off",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Quality your kids deserve.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "pulse",
    name: "Pulse Fitness",
    blurb: "Gym gear, supplements, sportswear, sneakers.",
    industry: "Sports",
    swatches: { primary: "#84cc16", bg: "#0a0a0a", text: "#f7fee7" },
    settings: {
      primary_color: "#84cc16",
      background_color: "#0a0a0a",
      text_color: "#f7fee7",
      accent_color: "#a3e635",
      card_background: "#171717",
      banner_url: "/landing/hero-seller.jpg",
      font_style: "bold",
      font_size: "large",
      layout: "horizontal",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "filled",
      card_border_radius: "lg",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "left",
      tagline: "Train harder, look sharper",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "normal",
      card_border: "light",
      card_shadow: "glow",
      container_width: "wide",
      product_image_ratio: "landscape",
      show_announcement: true,
      announcement_text: "No excuses, new gym drops every month",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Built for the grind.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "torque",
    name: "Torque Auto",
    blurb: "Car parts, accessories, detailing, auto care.",
    industry: "Auto",
    swatches: { primary: "#dc2626", bg: "#f8fafc", text: "#0f172a" },
    settings: {
      primary_color: "#dc2626",
      background_color: "#f8fafc",
      text_color: "#0f172a",
      accent_color: "#0f172a",
      card_background: "#ffffff",
      banner_url: null,
      font_style: "geometric",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "outlined",
      card_border_radius: "md",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "short",
      banner_overlay: false,
      header_style: "left",
      tagline: "Keep your ride running right",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "medium",
      card_shadow: "sm",
      container_width: "wide",
      product_image_ratio: "landscape",
      show_announcement: true,
      announcement_text: "Genuine parts only, fitting advice on WhatsApp",
      show_socials: false,
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Tested parts, straight talk.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "featured", visible: true },
      { type: "products", visible: true },
      { type: "banner", visible: false },
      { type: "socials", visible: false },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "verde",
    name: "Verde Garden",
    blurb: "Plants, seedlings, garden tools, green living.",
    industry: "Garden",
    swatches: { primary: "#4d7c0f", bg: "#f7fee7", text: "#1a2e05" },
    settings: {
      primary_color: "#4d7c0f",
      background_color: "#f7fee7",
      text_color: "#1a2e05",
      accent_color: "#65a30d",
      card_background: "#ffffff",
      banner_url: "/landing/sell-stall.jpg",
      font_style: "editorial",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "bordered",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Grow something beautiful",
      show_store_name: true,
      product_name_size: "medium",
      price_style: "bold",
      card_padding: "normal",
      card_border: "light",
      card_shadow: "sm",
      container_width: "normal",
      product_image_ratio: "portrait",
      show_announcement: false,
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "From our nursery to your home.",
    },
    sections: [
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "announcement", visible: false },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "sole-style",
    name: "Sole & Style",
    blurb: "Sneakers, slippers, footwear plug.",
    industry: "Footwear",
    swatches: { primary: "#1e3a8a", bg: "#eff6ff", text: "#172554" },
    settings: {
      primary_color: "#1e3a8a",
      background_color: "#eff6ff",
      text_color: "#172554",
      accent_color: "#f97316",
      card_background: "#ffffff",
      banner_url: "/landing/hero-seller.jpg",
      font_style: "bold",
      font_size: "large",
      layout: "grid3",
      image_shape: "rounded",
      spacing: "normal",
      card_style: "shadow",
      card_border_radius: "xl",
      product_name_weight: "bold",
      text_align: "left",
      banner_height: "tall",
      banner_overlay: true,
      header_style: "left",
      tagline: "Step correct, every day",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "normal",
      card_border: "none",
      card_shadow: "md",
      container_width: "wide",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Original pairs only, no stories",
      show_socials: true,
      social_style: "boxed",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Cop or cry.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "banner", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
  {
    id: "bag-lady",
    name: "Bag Lady",
    blurb: "Handbags, ankara bags, purses, luggage.",
    industry: "Bags",
    swatches: { primary: "#0f766e", bg: "#f0fdfa", text: "#134e4a" },
    settings: {
      primary_color: "#0f766e",
      background_color: "#f0fdfa",
      text_color: "#134e4a",
      accent_color: "#d97706",
      card_background: "#ffffff",
      banner_url: null,
      font_style: "elegant",
      font_size: "medium",
      layout: "grid",
      image_shape: "rounded",
      spacing: "relaxed",
      card_style: "bordered",
      card_border_radius: "lg",
      product_name_weight: "medium",
      text_align: "center",
      banner_height: "medium",
      banner_overlay: false,
      header_style: "centered",
      tagline: "Carry the culture with you",
      show_store_name: true,
      product_name_size: "large",
      price_style: "accent",
      card_padding: "relaxed",
      card_border: "accent",
      card_shadow: "sm",
      container_width: "normal",
      product_image_ratio: "portrait",
      show_announcement: true,
      announcement_text: "Owambe season? Matching sets available",
      show_socials: true,
      social_style: "pills",
      whatsapp_cta: true,
      show_stock_badge: true,
      footer_text: "Handpicked bags, fair prices.",
    },
    sections: [
      { type: "announcement", visible: true },
      { type: "header", visible: true },
      { type: "products", visible: true },
      { type: "featured", visible: true },
      { type: "banner", visible: false },
      { type: "socials", visible: true },
      { type: "footer", visible: true },
    ],
  },
];
